export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_BOOK_TEXT_SUCCESS = 'GET_BOOK_TEXT_SUCCESS';
export const GET_BOOK_TEXT_FAIL = 'GET_BOOK_TEXT_FAIL';
export const START = 'START';
export const STOP = 'STOP';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAIL = 'GET_BOOK_FAIL';
export const SET_ESTIMATE_SUCCESS = 'SET_ESTIMATE_SUCCESS';
export const SET_ESTIMATE_FAIL = 'SET_ESTIMATE_FAIL';


