export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';
export const GET_BOOK_TEXT_SUCCESS = 'GET_BOOK_TEXT_SUCCESS';
export const GET_BOOK_TEXT_FAIL = 'GET_BOOK_TEXT_FAIL';
export const START = 'START';
export const STOP = 'STOP';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAIL = 'GET_CATEGORY_FAIL';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAIL = 'GET_BOOK_FAIL';
export const SET_ESTIMATE_SUCCESS = 'SET_ESTIMATE_SUCCESS';
export const SET_ESTIMATE_FAIL = 'SET_ESTIMATE_FAIL';
export const SHOW_MODAL_SUCCESS = 'SHOW_MODAL_SUCCESS';
export const SHOW_MODAL_FAIL = 'SHOW_MODAL_FAIL';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAIL = 'POST_LOGIN_FAIL';
export const POST_SINGUP_SUCCESS = 'POST_SINGUP_SUCCESS';
export const POST_SINGUP_FAIL = 'POST_SINGUP_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const POST_RECOVERY_PASSWORD_SUCCESS = 'POST_RECOVERY_PASSWORD_SUCCESS';
export const POST_RECOVERY_PASSWORD_FAIL = 'POST_RECOVERY_PASSWORD_FAIL';
export const PUT_ADD_COMMENT_SUCCESS = 'PUT_ADD_COMMENT_SUCCESS';
export const PUT_ADD_COMMENT_FAIL = 'PUT_ADD_COMMENT_FAIL';
export const CHANGE_COMMENT_SUCCESS = 'CHANGE_COMMENT_SUCCESS';
export const CHANGE_COMMENT_FAIL = 'CHANGE_COMMENT_FAIL';
export const CHANGE_OFFICE_EMAIL_SUCCESS = 'CHANGE_OFFICE_EMAIL_SUCCESS';
export const CHANGE_OFFICE_PASSWORD_SUCCESS = 'CHANGE_OFFICE_PASSWORD_SUCCESS';
export const CHANGE_OFFICE_USERNAME_SUCCESS = 'CHANGE_OFFICE_USERNAME_SUCCESS';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_FAIL = 'GET_USER_BY_ID_FAIL';
export const CHANGE_EMAIL_LOGIN_SUCCESS = 'CHANGE_EMAIL_LOGIN_SUCCESS';
export const CHANGE_PASSWORD_LOGIN_SUCCESS = 'CHANGE_PASSWORD_LOGIN_SUCCESS';
export const CHANGE_EMAIL_SINGUP_SUCCESS = 'CHANGE_EMAIL_SINGUP_SUCCESS';
export const CHANGE_PASSWORD_SINGUP_SUCCESS = 'CHANGE_PASSWORD_SINGUP_SUCCESS';
export const CHANGE_EMAIL_PASS_REC_SUCCESS = 'CHANGE_EMAIL_SINGUP_SUCCESS';
export const CHANGE_LOAD_BOOK_TITLE_SUCCESS = 'CHANGE_LOAD_BOOK_TITLE_SUCCESS';
export const CHANGE_LOAD_BOOK_AUTHOR_SUCCESS = 'CHANGE_LOAD_BOOK_AUTHOR_SUCCESS';
export const CHANGE_LOAD_BOOK_GENRE_SUCCESS = 'CHANGE_LOAD_BOOK_GENRE_SUCCESS';
export const CHANGE_LOAD_BOOK_ISBN_SUCCESS = 'CHANGE_LOAD_BOOK_ISBN_SUCCESS';
export const CHANGE_LOAD_BOOK_ANNOTATION_SUCCESS = 'CHANGE_LOAD_BOOK_ANNOTATION_SUCCESS';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAIL = 'GET_COMMENTS_FAIL';
export const POST_OFFICE_SUCCESS = 'POST_OFFICE_SUCCESS';
export const POST_OFFICE_FAIL = 'POST_OFFICE_FAIL';
export const GET_MY_BOOKS_SUCCESS = 'GET_MY_BOOKS_SUCCESS';
export const GET_MY_BOOKS_FAIL = 'GET_MY_BOOKS_FAIL';







